# Generated by Django 4.0.4 on 2022-05-26 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primermvt', '0002_alter_primermvt_edad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='primermvt',
            name='edad',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='primermvt',
            name='nacimiento',
            field=models.CharField(max_length=10),
        ),
    ]
